name: AWS Î» Runtime
synopsis: Build fast and solid serverless applications
github: theam/aws-lambda-haskell-runtime
author: The Agile Monkeys
authorWebsite: https://www.theagilemonkeys.com
color: #662480
logo: https://i.imgur.com/I64VEiF.png
titleFont: Lato
bodyFont: Lato
