name: aws-lambda-haskell-runtime
version: 1.0.5
github: "theam/aws-lambda-haskell-runtime"
license: Apache-2.0
author: Nikita Tchayka
maintainer: hackers@theagilemonkeys.com
copyright: 2018 The Agile Monkeys SL

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: Haskell runtime for AWS Lambda
category: AWS
description: Please see the README on GitHub at <https://github.com/theam/aws-lambda-haskell-runtime#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - relude
  - wreq
  - microlens-platform
  - mtl
  - case-insensitive
  - process
  - optparse-generic
  - template-haskell
  - text
  - conduit
  - directory
  - filepath
  - uuid
  - time

library:
  source-dirs: src
  exposed-modules:
    - Aws.Lambda.Runtime
    - Aws.Lambda.Configuration

executables:
  bootstrap:
    source-dirs: app
    main: Main.hs
    dependencies:
      - aws-lambda-haskell-runtime

tests:
  aws-lambda-haskell-runtime-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aws-lambda-haskell-runtime
      - hspec
      - QuickCheck

default-extensions:
  - TemplateHaskell
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - NoImplicitPrelude
  - DeriveGeneric
  - TypeApplications

ghc-options:
  - -Wall
  - -Werror
  - -optP-Wno-nonportable-include-path
