name:                wai-app
version:             0.1.0.0
github:              "theam/aws-lambda-haskell-runtime"
license:             BSD3
author:              "Dobromir Nikolov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/theam/aws-lambda-haskell-runtime#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aws-lambda-haskell-runtime
- aws-lambda-haskell-runtime-wai
- text
- servant
- servant-server
- wai
- mtl

library:
  source-dirs: src

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-app

tests:
  lambda-testing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-app
